Repository hopesgit/futbol, pull requests merged in 2020-07, with the labels that each got.

#36 Create StatTracker Class and Tests
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#45 Import Game Teams data
  data/game_teams_fixture.csv
  lib/game_collection.rb
  lib/game_team.rb
  lib/game_team_collection.rb
  lib/team_collection.rb
  test/game_collection_test.rb
  test/game_team_collection_test.rb
  test/game_team_test.rb
  test/team_collection_test.rb
Labels: enhancement

#46 It2 - game stats: highest total score
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#50 Update game gameteam fixture files
  data/game_teams_fixture.csv
  data/games_fixture.csv
  lib/stat_tracker.rb
  test/game_collection_test.rb
  test/game_team_collection_test.rb
  test/stat_tracker_test.rb
Labels: bug

#53 It2 game avg goals by season
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#52 Game: Lowest_total_score and precentage_visitor_wins
  data/game_teams.csv
  data/game_teams_fixture.csv
  data/games_fixture.csv
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#56 It2 - league stats: count_of_teams
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#61 It2 league highest scoring home team
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#62 Update issue in team_collection required filepath
  lib/team_collection.rb
Labels: bug

#63 It2 league worst scoring home team
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#65 IT2 - Team - team_info and most_goals_scored
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#70 Season methods branch
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#71 IT2 - season stats: fewest_tackles
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#74 Rspec string/integer converter bug
  lib/game.rb
  lib/game_collection.rb
  lib/game_team.rb
  lib/game_team_collection.rb
  lib/team_collection.rb
  test/game_collection_test.rb
  test/game_team_collection_test.rb
  test/game_team_test.rb
  test/game_test.rb
  test/stat_tracker_test.rb
  test/team_collection_test.rb
  test/team_test.rb
Labels: bug

#75 Update any assertions calling an id as an integer to a string
  lib/game.rb
  lib/game_team.rb
  test/stat_tracker_test.rb
Labels: bug

#77 IT2 - team stats: avg win percentage
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#80 It3 gameteam seasonid refactor
  lib/game_collection.rb
  lib/game_team.rb
  lib/game_team_collection.rb
  lib/stat_tracker.rb
  test/game_collection_test.rb
  test/game_team_collection_test.rb
  test/game_team_test.rb
Labels: refactor

#83 Change team_id method and test keys to strings instead of symbols
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: bug

#85 IT2 - team stat: fewest goals scored
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#84 It2 season least accurate team
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#81 IT2 - team stats: rival
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#86 It2 most accurate team
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#90 Update test assertions for team_info to reflect updated attribute names
  test/stat_tracker_test.rb
Labels: bug

#91 Season and team methods added
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#95 Add best season method and test
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#94 Bug rival calculation
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: bug

#92 Update least_accurate_team to better conform to the spec
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: bug

#93 IT2: season - worst_coach
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: enhancement

#102 Collection refactor
  lib/game.rb
  lib/game_collection.rb
  lib/game_team.rb
  lib/game_team_collection.rb
  lib/stat_tracker.rb
  lib/team.rb
  lib/team_collection.rb
  test/game_collection_test.rb
  test/game_team_collection_test.rb
  test/game_team_test.rb
  test/game_test.rb
  test/stat_tracker_test.rb
  test/team_collection_test.rb
  test/team_test.rb
Labels: enhancement

#105 Small refactor
  lib/game.rb
  lib/helpable.rb
  lib/stat_tracker.rb
  lib/team.rb
  test/game_test.rb
  test/stat_tracker_test.rb
  test/team_test.rb
  test/test_helper.rb
Labels: refactor

#113 Refactor class methods
  lib/game.rb
  lib/game_team.rb
  lib/helpable.rb
  lib/stat_tracker.rb
  lib/team.rb
  test/game_team_test.rb
  test/game_test.rb
  test/stat_tracker_test.rb
  test/team_test.rb
Labels: refactor

#119 Don't require GameTeam within DataSet superclass
  lib/data_set.rb
Labels: bug

#123 small change to team_info
  lib/stat_tracker.rb
Labels: enhancement, refactor

#124 Revert from setup method in tests to class variable storage
  test/game_team_test.rb
  test/game_test.rb
  test/team_test.rb
Labels: refactor

#121 Mathable
  lib/game.rb
  lib/game_team.rb
  lib/helpable.rb
  lib/mathable.rb
  lib/stat_tracker.rb
  test/game_team_test.rb
  test/game_test.rb
  test/stat_tracker_test.rb
  test/team_test.rb
  test/test_helper.rb
Labels: enhancement

#125 Stub out test for favorite_opponent
  test/stat_tracker_test.rb
Labels: refactor
